- name: Modify developer server
  hosts: developerservers
  become: yes
  tasks:
    - name: Change text in the main page
      lineinfile:
          path: /home/ansible_controller/hello-world/src/App.js
          # The String to Search
          regexp: "Hello World!" 
          # The String to Replace
          line: "Hello DevOps!"
      #command: pwd
      #cat src/App.js | sed 's/Hello World!/Hello DevOps!/'
    #- name: Verify file modified
      #command: cat src/App.js

