name: Node Hello CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  job_test:
    name: Test hello app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./capstone_project/hello-world
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - name: Pull context hello app 
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        CI: true
    - run: npm install
    - run: npm run test

  job_build:
    needs: job_test
    if: success()
    name: Build app_hello' container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - name: Pull context hello app
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build the image
      run: docker build -t node_hello_app .
